package model.eo;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 10 10:04:23 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClassroomsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RoomNumber,
        GradeNumber;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROOMNUMBER = AttributesEnum.RoomNumber.index();
    public static final int GRADENUMBER = AttributesEnum.GradeNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ClassroomsImpl() {
    }

    /**
     * Gets the attribute value for RoomNumber, using the alias name RoomNumber.
     * @return the value of RoomNumber
     */
    public BigDecimal getRoomNumber() {
        return (BigDecimal) getAttributeInternal(ROOMNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoomNumber.
     * @param value value to set the RoomNumber
     */
    public void setRoomNumber(BigDecimal value) {
        setAttributeInternal(ROOMNUMBER, value);
    }

    /**
     * Gets the attribute value for GradeNumber, using the alias name GradeNumber.
     * @return the value of GradeNumber
     */
    public String getGradeNumber() {
        return (String) getAttributeInternal(GRADENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for GradeNumber.
     * @param value value to set the GradeNumber
     */
    public void setGradeNumber(String value) {
        setAttributeInternal(GRADENUMBER, value);
    }

    /**
     * @param roomNumber key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal roomNumber) {
        return new Key(new Object[] { roomNumber });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.Classrooms");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        setGradeNumber("G1");
    }
}

